<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ExerciseEntitySeeder extends Seeder
{
    /**
     * insertar datos de ejemplo en la tabla de ejercicios
     */
    public function run(): void
    {
        DB::table('exercise_table')->insert([
            ['id' => 1, 'name' => 'Flexiones', 'description' => 'Empuje para pecho, tríceps y hombros.', 'imageUri' => 'https://cdn.businessinsider.es/sites/navi.axelspringer.es/public/media/image/2021/05/hombre-haciendo-flexiones-2334495.jpg?tf=3840x'],
            ['id' => 2, 'name' => 'Planchas', 'description' => 'Isométrico para core y abdomen.', 'imageUri' => 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/mid-adult-man-doing-plank-exercise-royalty-free-image-1585917009.jpg?resize=980:*'],
            ['id' => 3, 'name' => 'Press de banca', 'description' => 'Fuerza para pecho, hombros y tríceps.', 'imageUri' => 'https://th.bing.com/th/id/OIP.HyQ1pPJDa9_X4b8lGMkTAgAAAA?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 4, 'name' => 'Remo con mancuernas', 'description' => 'Ejercicio para espalda usando mancuernas.', 'imageUri' => 'https://i.blogs.es/0c2131/remo-con-mancuerna/1366_2000.jpg'],
            ['id' => 5, 'name' => 'Peso muerto', 'description' => 'Levantamiento de barra desde el suelo.', 'imageUri' => 'https://i.blogs.es/d61882/istock-891602094/840_560.jpg'],
            ['id' => 6, 'name' => 'Zancadas', 'description' => 'Paso largo hacia adelante alternando piernas.', 'imageUri' => 'https://th.bing.com/th/id/OIP.Qfl_I5xnntRLzqbvDwrKggHaE8?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 7, 'name' => 'Crunch abdominal', 'description' => 'Flexión de tronco para trabajar abdominales.', 'imageUri' => 'https://th.bing.com/th/id/OIP.pQr0tNiw5FN3GGYxmhcLgAHaEG?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 8, 'name' => 'Elevación de piernas', 'description' => 'Levantar piernas tumbado para abdomen.', 'imageUri' => 'https://th.bing.com/th/id/OIP.8ImjYHon-Ce1oqntSTSbJQHaEK?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 9, 'name' => 'Oblicuos', 'description' => 'Ejercicio para los músculos laterales del abdomen.', 'imageUri' => 'https://th.bing.com/th/id/OIP.nVRIybSfE2_2NJhlcz4HJwHaE8?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 10, 'name' => 'Dominadas', 'description' => 'Elevar el cuerpo sujetándose de una barra.', 'imageUri' => 'https://th.bing.com/th/id/R.d0a38f5436ffe4f9b9e228812f32bf4c?rik=Eq7bU1gO76WRAQ&pid=ImgRaw&r=0'],
            ['id' => 11, 'name' => 'Fondos de tríceps', 'description' => 'Bajar y subir el cuerpo apoyado en bancos.', 'imageUri' => 'https://www.budujmase.pl/wp-content/uploads/Fotolia_125425082_Subscription_Monthly_M.jpg'],
            ['id' => 12, 'name' => 'Sentadillas', 'description' => 'Flexión de rodillas bajando la cadera.', 'imageUri' => 'https://th.bing.com/th/id/OIP.uSNK5ejNHJuvUNJTZTlFxAHaE8?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 13, 'name' => 'Burpees', 'description' => 'Ejercicio completo con salto y flexión.', 'imageUri' => 'https://th.bing.com/th/id/OIP.nsM5VbX_M_dTgumyHkvw4gHaE8?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 14, 'name' => 'Mountain Climbers', 'description' => 'Simular correr en posición de plancha.', 'imageUri' => 'https://th.bing.com/th/id/OIP.jte_9EQOzW9IzrOulm5WZQHaEK?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 15, 'name' => 'Press militar', 'description' => 'Empuje de barra o mancuernas sobre la cabeza.', 'imageUri' => 'https://th.bing.com/th/id/OIP.XUUqDUD7Yy4GwwDOVsi0rAHaE8?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 16, 'name' => 'Russian Twists', 'description' => 'Giro de torso sentado para abdominales.', 'imageUri' => 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/rtwist1-jpg-1570636420.jpg'],
            ['id' => 17, 'name' => 'Curl de bíceps', 'description' => 'Flexión de codo con peso para bíceps.', 'imageUri' => 'https://th.bing.com/th/id/OIP.pQ4HUzzdxEOpyAkBj4eT4wHaEo?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 18, 'name' => 'Jump Squats', 'description' => 'Sentadilla seguida de salto explosivo.', 'imageUri' => 'https://th.bing.com/th/id/OIP.f5lIwj2xhpn98MPKbCbg8wHaEJ?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 19, 'name' => 'Dead Bug', 'description' => 'Coordinar brazos y piernas tumbado para core.', 'imageUri' => 'https://th.bing.com/th/id/OIP.hw7NgxFnAu-15TH8nnzHhQHaEK?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 20, 'name' => 'Hip Thrust', 'description' => 'Elevación de cadera apoyando la espalda.', 'imageUri' => 'https://th.bing.com/th/id/OIP.GjwYFd-J7aJDoLFvyLEevAHaEG?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 21, 'name' => 'Skipping', 'description' => 'Correr en el sitio elevando rodillas.', 'imageUri' => 'https://th.bing.com/th/id/OIP.rp3xv5pKVNIXVo19fj6fZAHaEK?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 22, 'name' => 'Curl de tríceps', 'description' => 'Extensión de codo con peso para tríceps.', 'imageUri' => 'https://www.sportlife.es/uploads/static/sportlife/upload/images/paragrapharticle/14069/paragrapharticle-14627-595a0ae842bc0.jpg'],
            ['id' => 23, 'name' => 'Salto al cajón', 'description' => 'Saltar con ambos pies sobre un cajón.', 'imageUri' => 'https://giansalud.com/wp-content/uploads/2023/12/20.1-box-jump-salto-al-cajon-isquiotibiales-isquisurales-powerlifting-gian-salud-gianfranco-slepetis-ezequiel-costa-uguet.webp'],
            ['id' => 24, 'name' => 'Press Arnold', 'description' => 'Press de hombros girando las mancuernas.', 'imageUri' => 'https://th.bing.com/th/id/OIP.Sjx_iZM0G8REx9Hqr7gwAwHaFv?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 25, 'name' => 'Remo con barra', 'description' => 'Tirar de una barra hacia el abdomen.', 'imageUri' => 'https://th.bing.com/th/id/OIP.yvXLm0IMGERm1u5zfc-eYgHaFE?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 26, 'name' => 'Patada de glúteo', 'description' => 'Extensión de pierna hacia atrás en cuadrupedia.', 'imageUri' => 'https://i.ytimg.com/vi/lHMhOUVUwf0/maxresdefault.jpg'],
            ['id' => 27, 'name' => 'Elevación de talones', 'description' => 'Subir y bajar talones para trabajar gemelos.', 'imageUri' => 'https://th.bing.com/th/id/OIP.b-mxdK0IbS211YVNzP8POQHaHa?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 28, 'name' => 'Face Pulls', 'description' => 'Tirar de una cuerda hacia la cara para hombros.', 'imageUri' => 'https://cdn.mos.cms.futurecdn.net/3ZAEXcd7cA3W2fMrVQY9EE-1200-80.jpg'],
            ['id' => 29, 'name' => 'Jumping Jacks', 'description' => 'Saltos abriendo piernas y brazos.', 'imageUri' => 'https://www.eatthis.com/wp-content/uploads/sites/4/2023/03/man-jumping-jacks.jpg?quality=82&strip=all'],
            ['id' => 30, 'name' => 'Ab Wheel', 'description' => 'Rodar una rueda abdominal desde rodillas.', 'imageUri' => 'https://th.bing.com/th/id/OIP.jjff0VOQd_8Xqc1fVcS5mgHaHa?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 31, 'name' => 'Peso muerto sumo', 'description' => 'Peso muerto con piernas abiertas.', 'imageUri' => 'https://i.ytimg.com/vi/sa5V3GXupFE/maxresdefault.jpg'],
            ['id' => 32, 'name' => 'Flexiones diamante', 'description' => 'Flexiones con manos juntas en forma de diamante.', 'imageUri' => 'https://static.nike.com/a/images/f_auto/dpr_1.0,cs_srgb/h_2432,c_limit/5afb0e80-d6e1-4921-9852-48f28fc2a537/%C2%BFqu%C3%A9-m%C3%BAsculos-trabajan-las-flexiones-diamante-y-c%C3%B3mo-se-hacen.jpg'],
            ['id' => 33, 'name' => 'Prensa de piernas', 'description' => 'Empuje de peso con las piernas en máquina.', 'imageUri' => 'https://www.musculaciontotal.com/wp-content/uploads/2016/01/prensa-de-piernas.jpg'],
            ['id' => 34, 'name' => 'Dragon Flags', 'description' => 'Elevación de cuerpo para trabajar el core.', 'imageUri' => 'https://th.bing.com/th/id/OIP.dhnlXYxSBzPzuSlwHsi4gwHaFj?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 35, 'name' => 'Press de hombros con mancuernas', 'description' => 'Empuje de mancuernas sobre la cabeza.', 'imageUri' => 'https://s3.amazonaws.com/prod.skimble/assets/2193622/image_iphone.jpg'],
            ['id' => 36, 'name' => 'Dorsales en polea', 'description' => 'Jalón en polea para espalda.', 'imageUri' => 'https://hablandofitness.com/wp-content/uploads/2019/03/polea-alta-para-dorsales-1024x576.jpg'],
            ['id' => 37, 'name' => 'Step-ups', 'description' => 'Subir a un banco alternando piernas.', 'imageUri' => 'https://app-media.fitbod.me/v2/128/images/landscape/0_960x540.jpg'],
            ['id' => 38, 'name' => 'Flexiones con palmada', 'description' => 'Flexión seguida de palmada en el aire.', 'imageUri' => 'https://i.ytimg.com/vi/t9ZKe3FQhpA/maxresdefault.jpg'],
            ['id' => 39, 'name' => 'Kettlebell Swings', 'description' => 'Balanceo de pesa rusa entre las piernas.', 'imageUri' => 'https://th.bing.com/th/id/OIP.mFHY7m6fTc0RZWt1IdvLoAHaE8?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 40, 'name' => 'Plancha lateral', 'description' => 'Soporte lateral del cuerpo en antebrazo.', 'imageUri' => 'https://media.gq.com.mx/photos/5f934d11c10dacf7b3e87a6a/master/w_1600%2Cc_limit/plancha%2520lateral.jpg'],
            ['id' => 41, 'name' => 'Jump Rope', 'description' => 'Saltar la cuerda para cardio.', 'imageUri' => 'https://www.mensjournal.com/.image/t_share/MTk2MTM3MzM5NDk5NTIxMTY5/africanamericanathletemanworkingoutonaskippingrope.jpg'],
            ['id' => 42, 'name' => 'Band Pull Aparts', 'description' => 'Separar banda elástica con los brazos.', 'imageUri' => 'https://barbellrehab.com/wp-content/uploads/2016/10/supinated-band-pull-apart.jpg'],
            ['id' => 43, 'name' => 'Goblet Squat', 'description' => 'Sentadilla sujetando peso al pecho.', 'imageUri' => 'https://images.squarespace-cdn.com/content/v1/5020b649e4b03f6f4d19970a/1404662948578-DEB43OYCQI4W4ND8WZY8/Personal+Trainer+Goblet+Squatting'],
            ['id' => 44, 'name' => 'Press de banca inclinado', 'description' => 'Empuje de barra en banco inclinado.', 'imageUri' => 'https://i.ytimg.com/vi/DJNzKiiysgI/maxresdefault.jpg'],
            ['id' => 45, 'name' => 'Remo en máquina', 'description' => 'Tirar de manijas en máquina para espalda.', 'imageUri' => 'https://e00-expansion.uecdn.es/assets/multimedia/imagenes/2023/05/05/16832486070332.jpg'],
            ['id' => 46, 'name' => 'Curl martillo', 'description' => 'Flexión de codo con mancuernas neutras.', 'imageUri' => 'https://weriselatam.com/wp-content/uploads/2020/09/Curl-martillo-1160x820.jpg'],
            ['id' => 47, 'name' => 'Sentadilla sumo', 'description' => 'Sentadilla con piernas abiertas.', 'imageUri' => 'https://th.bing.com/th/id/OIP.wumlp9DxeRV5dyst8YSI2AHaE8?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 48, 'name' => 'Flexiones tipo Spiderman', 'description' => 'Flexión llevando rodilla al codo.', 'imageUri' => 'https://th.bing.com/th/id/OIP.5ekUBrqvO-zWXTzjZCxGnwAAAA?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 49, 'name' => 'Paseo del granjero', 'description' => 'Caminar cargando peso en ambas manos.', 'imageUri' => 'https://www.vitobest.com/blog/wp-content/uploads/2019/03/Farmer-walk_2.jpg'],
            ['id' => 50, 'name' => 'Elevaciones laterales', 'description' => 'Levantar mancuernas lateralmente para hombros.', 'imageUri' => 'https://th.bing.com/th/id/OIP.g6W6Awse1R728fVGSJ5CTwHaEl?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 51, 'name' => 'Jump Lunges', 'description' => 'Zancadas alternas con salto.', 'imageUri' => 'https://th.bing.com/th/id/OIP.TARugiqE9s0XwxfjAWYDogHaD3?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 52, 'name' => 'Dragon Walks', 'description' => 'Caminar en posición baja para core y piernas.', 'imageUri' => 'https://i.ytimg.com/vi/FzVwdPRJLO4/maxresdefault.jpg'],
            ['id' => 53, 'name' => 'Face Pulls con cuerda', 'description' => 'Tirar de cuerda hacia la cara.', 'imageUri' => 'https://i.ytimg.com/vi/ymBsUknTFdE/maxresdefault.jpg'],
            ['id' => 54, 'name' => 'Prensa de piernas inclinada', 'description' => 'Empuje de piernas en máquina inclinada.', 'imageUri' => 'https://th.bing.com/th/id/R.c3fc096943da4b94a3082d16c3540ac3?rik=tAMtLGds9aGq5A&pid=ImgRaw&r=0'],
            ['id' => 55, 'name' => 'Dominadas negativas', 'description' => 'Bajar lentamente desde barra.', 'imageUri' => 'https://mejorconsalud.as.com/wp-content/uploads/2021/05/dominadas-negativas-768x512.png'],
            ['id' => 56, 'name' => 'Tijeras abdominales', 'description' => 'Cruzar piernas alternando en el aire.', 'imageUri' => 'https://i.ytimg.com/vi/iQz5ghrm0qM/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGGUgZShlMA8=&rs=AOn4CLDYajoAgUrtq0rOvA8K2iwTtbmZEw'],
            ['id' => 57, 'name' => 'Extensiones de espalda', 'description' => 'Elevar el torso tumbado boca abajo.', 'imageUri' => 'https://th.bing.com/th/id/OIP.yfn69-sSHEy4GzNRcthBJQHaHa?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 58, 'name' => 'Squats con salto lateral', 'description' => 'Sentadilla seguida de salto lateral.', 'imageUri' => 'https://i.ytimg.com/vi/TfkoFX4s_OE/maxresdefault.jpg'],
            ['id' => 59, 'name' => 'Kettlebell Deadlifts', 'description' => 'Peso muerto con pesa rusa.', 'imageUri' => 'https://th.bing.com/th/id/OIP.uv50xP3J9ABZ9ryE2YqvagHaEK?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 60, 'name' => 'Plancha con elevación de brazo', 'description' => 'Levantar un brazo en plancha.', 'imageUri' => 'https://th.bing.com/th/id/OIP.gK2lZhrhiJ5K9BEFoJZq5wAAAA?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 61, 'name' => 'Sprint en cinta', 'description' => 'Correr rápido en cinta.', 'imageUri' => 'https://objetivofitness.com/wp-content/uploads/2022/12/hiit-en-cinta-correr-ejemplos.jpg'],
            ['id' => 62, 'name' => 'Press de banca con agarre cerrado', 'description' => 'Empuje de barra con manos juntas.', 'imageUri' => 'https://mundoentrenamiento.com/wp-content/uploads/2017/11/Press-de-banca-agarre-cerrado.jpg'],
            ['id' => 63, 'name' => 'Remo invertido', 'description' => 'Tirar del cuerpo hacia barra baja.', 'imageUri' => 'https://www.musculaciontotal.com/wp-content/uploads/2018/04/EL-REMO-INVERTIDO.jpg'],
            ['id' => 64, 'name' => 'Sentadillas búlgaras', 'description' => 'Sentadilla con un pie elevado atrás.', 'imageUri' => 'https://www.aixafitness.com/wp-content/uploads/2023/09/como-hacer-sentadillas-bulgaras-en-casa-y-en-el-gym-con-o-sin-mancuernas.jpg'],
            ['id' => 65, 'name' => 'Elevación de rodillas colgado', 'description' => 'Subir rodillas colgado de barra.', 'imageUri' => 'https://th.bing.com/th/id/OIP.xmlJjQvGSJTpJiFDx1b9GwHaD4?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 66, 'name' => 'Clean and Press', 'description' => 'Levantar y empujar peso sobre cabeza.', 'imageUri' => 'https://th.bing.com/th/id/OIP.JDAfPmaHmoB9lkWwVTXI6wHaEK?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 67, 'name' => 'Dominadas con agarre supino', 'description' => 'Dominadas con palmas hacia ti.', 'imageUri' => 'https://th.bing.com/th/id/OIP.8mqTf-W4gTaFtVzoWMDusAHaEK?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 68, 'name' => 'Golpe de martillo con neumático', 'description' => 'Golpear neumático con martillo.', 'imageUri' => 'https://th.bing.com/th/id/OIP.N3s37a-1PEaslw1_-3A9BQHaE8?r=0&o=7rm=3&rs=1&pid=ImgDetMain'],
            ['id' => 69, 'name' => 'Peso muerto rumano', 'description' => 'Peso muerto con piernas semi-extendidas.', 'imageUri' => 'https://th.bing.com/th/id/OIP.HloSuZbI5WQi5V6SoUSsbAHaHa?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 70, 'name' => 'Flexiones con TRX', 'description' => 'Flexiones usando bandas TRX.', 'imageUri' => 'https://i.ytimg.com/vi/zgQxerFsPxQ/maxresdefault.jpg'],
            ['id' => 71, 'name' => 'Battle Ropes', 'description' => 'Agitar cuerdas gruesas para cardio.', 'imageUri' => 'https://mirafit.co.uk/wp/wp-content/uploads/2023/06/battle-rope-slams-with-Mirafit-Battle-Rope-1024x681.jpg'],
            ['id' => 72, 'name' => 'Elevación de talones con peso', 'description' => 'Subir talones sosteniendo peso.', 'imageUri' => 'https://th.bing.com/th/id/OIP.S-9cESMZPxsizRYPUIiGBwAAAA?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 73, 'name' => 'Press de banca con mancuernas', 'description' => 'Empuje de mancuernas en banco.', 'imageUri' => 'https://th.bing.com/th/id/OIP.ONF4hwBsMI05nplkdVIHegHaEK?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 74, 'name' => 'Step-ups con peso', 'description' => 'Subir a banco con peso.', 'imageUri' => 'https://hdstatic.net/gridfs/holadoctor/51e68c7cb937954f692d2ce2_4_41-1374064428.jpg'],
            ['id' => 75, 'name' => 'Plancha con toque de hombros', 'description' => 'Tocar hombro opuesto en plancha.', 'imageUri' => 'https://i.ytimg.com/vi/m5ehtKmixTc/maxresdefault.jpg'],
            ['id' => 76, 'name' => 'Snatch con mancuerna', 'description' => 'Levantar mancuerna de suelo a arriba.', 'imageUri' => 'https://i.ytimg.com/vi/dmQHHxZ0WDI/maxresdefault.jpg'],
            ['id' => 77, 'name' => 'Dominadas con lastre', 'description' => 'Dominadas con peso extra.', 'imageUri' => 'https://th.bing.com/th/id/OIP.8ALnjCpFUwmb6VaAmzpgzQAAAA?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 78, 'name' => 'Golpe de balón medicinal', 'description' => 'Lanzar balón medicinal al suelo.', 'imageUri' => 'https://essentialtraining.es/wp-content/uploads/2021/04/balon-medicinal-e1618485001501.jpg'],
            ['id' => 79, 'name' => 'Sentadillas pistol', 'description' => 'Sentadilla a una pierna.', 'imageUri' => 'https://i.ytimg.com/vi/wWaKGvR40C0/maxresdefault.jpg'],
            ['id' => 80, 'name' => 'Plancha con giro de torso', 'description' => 'Girar torso en posición de plancha.', 'imageUri' => 'https://i.ytimg.com/vi/WCqcqoojNcY/maxresdefault.jpg'],
            ['id' => 81, 'name' => 'Salto lateral con banda', 'description' => 'Saltar lateralmente con banda elástica.', 'imageUri' => 'https://i.ytimg.com/vi/9AHnDT4mqrg/maxresdefault.jpg'],
            ['id' => 82, 'name' => 'Press de pecho con banda de resistencia', 'description' => 'Empuje de banda para pecho.', 'imageUri' => 'https://www.mundodeportivo.com/files/image_449_220/files/fp/uploads/2022/12/27/63aaf763c1cb6.r_d.512-342.png'],
            ['id' => 83, 'name' => 'Remo con kettlebell', 'description' => 'Remo con pesa rusa para espalda.', 'imageUri' => 'https://i.ytimg.com/vi/rRh_ffZKYfk/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGGUgYChUMA8=&rs=AOn4CLBFNK2u_-FZStd8zQTt6UhqkPet4Q'],
            ['id' => 84, 'name' => 'Sentadilla con balón medicinal', 'description' => 'Sentadilla usando balón medicinal.', 'imageUri' => 'https://th.bing.com/th/id/OIP.VUWaej9_7-drakXxO0SZNAHaE8?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 85, 'name' => 'Flexiones explosivas', 'description' => 'Flexiones con impulso rápido.', 'imageUri' => 'https://th.bing.com/th/id/OIP.4BFXrOOO2Z5tBioAsDAT8gHaE7?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 86, 'name' => 'Elevación de piernas en barra', 'description' => 'Subir piernas colgado de barra.', 'imageUri' => 'https://th.bing.com/th/id/OIP.Zc1-w5kI9zUqbrA7dzWieQHaEK?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 87, 'name' => 'Plancha con desplazamiento', 'description' => 'Moverse lateralmente en plancha.', 'imageUri' => 'https://i.ytimg.com/vi/wdKqEigStig/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AHUBoAC4AOKAgwIABABGFQgZShAMA8=&rs=AOn4CLC212vAKYnPJ15YFN74IpSJ52pmFg'],
            ['id' => 88, 'name' => 'Swing con kettlebell a una mano', 'description' => 'Balanceo de pesa rusa con una mano.', 'imageUri' => 'https://i.ytimg.com/vi/4exhyrM4ioE/maxresdefault.jpg'],
            ['id' => 89, 'name' => 'Curl de bíceps en banco inclinado', 'description' => 'Curl de bíceps en banco inclinado.', 'imageUri' => 'https://i.ytimg.com/vi/iYYCdOCSsss/maxresdefault.jpg'],
            ['id' => 90, 'name' => 'Step-ups con barra', 'description' => 'Subir a banco con barra.', 'imageUri' => 'https://i.ytimg.com/vi/7zG2xWEZgEY/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGF0gRyhyMA8=&rs=AOn4CLDqDMH0L0XgMjaXXs34O904u5rX8A'],
            ['id' => 91, 'name' => 'Jumping lunges con mancuernas', 'description' => 'Zancadas con salto y mancuernas.', 'imageUri' => 'https://i.ytimg.com/vi/22HS4BDFW9o/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGGkgaShpMA8=&rs=AOn4CLD76cmYeARLgEDnEidvdWs6CAQ3Wg'],
            ['id' => 92, 'name' => 'Remo con polea baja', 'description' => 'Remo en máquina de polea baja.', 'imageUri' => 'https://th.bing.com/th/id/OIP.UEBGGdT8uFuo_gafnN5DbAHaEK?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 93, 'name' => 'Sentadilla lateral', 'description' => 'Sentadilla desplazando lateralmente.', 'imageUri' => 'https://th.bing.com/th/id/OIP.Wt1Q5oOZI3VdPl681F8P2gHaEK?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 94, 'name' => 'Flexión en anillas', 'description' => 'Flexiones usando anillas.', 'imageUri' => 'https://th.bing.com/th/id/OIP._46ptS0XwNtxyDckPYaOVgHaEK?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 95, 'name' => 'Fondos en paralelas con peso', 'description' => 'Fondos en paralelas con peso extra.', 'imageUri' => 'https://i0.wp.com/streetliftingacademy.com/wp-content/uploads/2021/07/streetlifting-1.png?w=1080&ssl=1'],
            ['id' => 96, 'name' => 'Dragon Squat', 'description' => 'Sentadilla avanzada a una pierna.', 'imageUri' => 'https://th.bing.com/th/id/OIP.EuP34n8bAuVhEUvO3AhQ3QHaEg?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 97, 'name' => 'Press de hombros con barra', 'description' => 'Empuje de barra sobre la cabeza.', 'imageUri' => 'https://th.bing.com/th/id/OIP.-GuWn7MaoV7Cef4hmiS77gHaE8?r=0&rs=1&pid=ImgDetMain'],
            ['id' => 98, 'name' => 'Plancha con elevación de piernas', 'description' => 'Levantar piernas en plancha.', 'imageUri' => 'https://th.bing.com/th/id/OIP.F0REe47wLKC1YnKmX-zOHgHaEK?r=0&o=7rm=3&rs=1&pid=ImgDetMain'],
            ['id' => 99, 'name' => 'Sprint con trineo', 'description' => 'Correr empujando un trineo.', 'imageUri' => 'https://i.ytimg.com/vi/AYZppYGK9tc/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGGUgYSgkMA8=&rs=AOn4CLD8s9O12Cg41hlV8026OfLN394B7w'],
            ['id' => 100, 'name' => 'Desplantes laterales con peso', 'description' => 'Desplantes laterales con peso.', 'imageUri' => 'https://aws.glamour.mx/prod/designs/v1/assets/620x620/221260.jpg'],
        ]);
    }
}
