<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ExerciseEntitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('exercise_table')->insert([
            ['id' => 1, 'name' => 'Flexiones', 'description' => '4x12 repeticiones', 'image_uri' => ''],
            ['id' => 2, 'name' => 'Planchas', 'description' => '3x60 segundos', 'image_uri' => ''],
            ['id' => 3, 'name' => 'Press de banca', 'description' => '4x10 repeticiones', 'image_uri' => ''],
            ['id' => 4, 'name' => 'Remo con mancuernas', 'description' => '3x12 repeticiones', 'image_uri' => ''],
            ['id' => 5, 'name' => 'Peso muerto', 'description' => '4x8 repeticiones', 'image_uri' => ''],
            ['id' => 6, 'name' => 'Zancadas', 'description' => '3x12 cada pierna', 'image_uri' => ''],
            ['id' => 7, 'name' => 'Crunch abdominal', 'description' => '4x20 repeticiones', 'image_uri' => ''],
            ['id' => 8, 'name' => 'Elevación de piernas', 'description' => '3x15 repeticiones', 'image_uri' => ''],
            ['id' => 9, 'name' => 'Oblicuos', 'description' => '3x20 repeticiones', 'image_uri' => ''],
            ['id' => 10, 'name' => 'Dominadas', 'description' => '4x8 repeticiones', 'image_uri' => ''],
            ['id' => 11, 'name' => 'Fondos de tríceps', 'description' => '3x10 repeticiones', 'image_uri' => ''],
            ['id' => 12, 'name' => 'Sentadillas', 'description' => '4x12 repeticiones', 'image_uri' => ''],
            ['id' => 13, 'name' => 'Burpees', 'description' => '3x15 repeticiones', 'image_uri' => ''],
            ['id' => 14, 'name' => 'Mountain Climbers', 'description' => '4x30 segundos', 'image_uri' => ''],
            ['id' => 15, 'name' => 'Press militar', 'description' => '3x10 repeticiones', 'image_uri' => ''],
            ['id' => 16, 'name' => 'Russian Twists', 'description' => '3x20 repeticiones', 'image_uri' => ''],
            ['id' => 17, 'name' => 'Curl de bíceps', 'description' => '3x12 repeticiones', 'image_uri' => ''],
            ['id' => 18, 'name' => 'Jump Squats', 'description' => '3x10 repeticiones', 'image_uri' => ''],
            ['id' => 19, 'name' => 'Dead Bug', 'description' => '3x15 repeticiones', 'image_uri' => ''],
            ['id' => 20, 'name' => 'Hip Thrust', 'description' => '4x12 repeticiones', 'image_uri' => ''],
            ['id' => 21, 'name' => 'Skipping', 'description' => '3x60 segundos', 'image_uri' => ''],
            ['id' => 22, 'name' => 'Curl de tríceps', 'description' => '3x10 repeticiones', 'image_uri' => ''],
            ['id' => 23, 'name' => 'Salto al cajón', 'description' => '3x12 repeticiones', 'image_uri' => ''],
            ['id' => 24, 'name' => 'Press Arnold', 'description' => '4x10 repeticiones', 'image_uri' => ''],
            ['id' => 25, 'name' => 'Remo con barra', 'description' => '3x12 repeticiones', 'image_uri' => ''],
            ['id' => 26, 'name' => 'Patada de glúteo', 'description' => '3x15 cada pierna', 'image_uri' => ''],
            ['id' => 27, 'name' => 'Elevación de talones', 'description' => '4x20 repeticiones', 'image_uri' => ''],
            ['id' => 28, 'name' => 'Face Pulls', 'description' => '3x12 repeticiones', 'image_uri' => ''],
            ['id' => 29, 'name' => 'Jumping Jacks', 'description' => '4x30 segundos', 'image_uri' => ''],
            ['id' => 30, 'name' => 'Ab Wheel', 'description' => '3x10 repeticiones', 'image_uri' => ''],
            ['id' => 31, 'name' => 'Peso muerto sumo', 'description' => '4x8 repeticiones', 'image_uri' => ''],
            ['id' => 32, 'name' => 'Flexiones diamante', 'description' => '3x12 repeticiones', 'image_uri' => ''],
            ['id' => 33, 'name' => 'Prensa de piernas', 'description' => '4x10 repeticiones', 'image_uri' => ''],
            ['id' => 34, 'name' => 'Dragon Flags', 'description' => '3x8 repeticiones', 'image_uri' => ''],
            ['id' => 35, 'name' => 'Press de hombros con mancuernas', 'description' => '4x10 repeticiones', 'image_uri' => ''],
            ['id' => 36, 'name' => 'Dorsales en polea', 'description' => '3x12 repeticiones', 'image_uri' => ''],
            ['id' => 37, 'name' => 'Step-ups', 'description' => '3x10 cada pierna', 'image_uri' => ''],
            ['id' => 38, 'name' => 'Flexiones con palmada', 'description' => '3x10 repeticiones', 'image_uri' => ''],
            ['id' => 39, 'name' => 'Kettlebell Swings', 'description' => '4x15 repeticiones', 'image_uri' => ''],
            ['id' => 40, 'name' => 'Plancha lateral', 'description' => '3x45 segundos cada lado', 'image_uri' => ''],
            ['id' => 41, 'name' => 'Jump Rope', 'description' => '4x60 segundos', 'image_uri' => ''],
            ['id' => 42, 'name' => 'Band Pull Aparts', 'description' => '3x15 repeticiones', 'image_uri' => ''],
            ['id' => 43, 'name' => 'Goblet Squat', 'description' => '4x12 repeticiones', 'image_uri' => ''],
            ['id' => 44, 'name' => 'Press de banca inclinado', 'description' => '3x10 repeticiones', 'image_uri' => ''],
            ['id' => 45, 'name' => 'Remo en máquina', 'description' => '4x12 repeticiones', 'image_uri' => ''],
            ['id' => 46, 'name' => 'Curl martillo', 'description' => '3x12 repeticiones', 'image_uri' => ''],
            ['id' => 47, 'name' => 'Sentadilla sumo', 'description' => '3x10 repeticiones', 'image_uri' => ''],
            ['id' => 48, 'name' => 'Flexiones tipo Spiderman', 'description' => '3x10 cada lado', 'image_uri' => ''],
            ['id' => 49, 'name' => 'Paseo del granjero', 'description' => '3x30 metros', 'image_uri' => ''],
            ['id' => 50, 'name' => 'Elevaciones laterales', 'description' => '4x12 repeticiones', 'image_uri' => ''],
            ['id' => 51, 'name' => 'Jump Lunges', 'description' => '3x12 cada pierna', 'image_uri' => ''],
            ['id' => 52, 'name' => 'Dragon Walks', 'description' => '4x10 pasos', 'image_uri' => ''],
            ['id' => 53, 'name' => 'Face Pulls con cuerda', 'description' => '3x15 repeticiones', 'image_uri' => ''],
            ['id' => 54, 'name' => 'Prensa de piernas inclinada', 'description' => '4x10 repeticiones', 'image_uri' => ''],
            ['id' => 55, 'name' => 'Dominadas negativas', 'description' => '3x8 repeticiones', 'image_uri' => ''],
            ['id' => 56, 'name' => 'Tijeras abdominales', 'description' => '4x20 repeticiones', 'image_uri' => ''],
            ['id' => 57, 'name' => 'Extensiones de espalda', 'description' => '3x12 repeticiones', 'image_uri' => ''],
            ['id' => 58, 'name' => 'Squats con salto lateral', 'description' => '3x12 repeticiones', 'image_uri' => ''],
            ['id' => 59, 'name' => 'Kettlebell Deadlifts', 'description' => '4x10 repeticiones', 'image_uri' => ''],
            ['id' => 60, 'name' => 'Plancha con elevación de brazo', 'description' => '3x30 segundos cada lado', 'image_uri' => ''],
            ['id' => 61, 'name' => 'Sprint en cinta', 'description' => '4x30 segundos', 'image_uri' => ''],
            ['id' => 62, 'name' => 'Press de banca con agarre cerrado', 'description' => '3x10 repeticiones', 'image_uri' => ''],
            ['id' => 63, 'name' => 'Remo invertido', 'description' => '3x12 repeticiones', 'image_uri' => ''],
            ['id' => 64, 'name' => 'Sentadillas búlgaras', 'description' => '3x10 cada pierna', 'image_uri' => ''],
            ['id' => 65, 'name' => 'Elevación de rodillas colgado', 'description' => '4x15 repeticiones', 'image_uri' => ''],
            ['id' => 66, 'name' => 'Clean and Press', 'description' => '3x8 repeticiones', 'image_uri' => ''],
            ['id' => 67, 'name' => 'Dominadas con agarre supino', 'description' => '4x10 repeticiones', 'image_uri' => ''],
            ['id' => 68, 'name' => 'Golpe de martillo con neumático', 'description' => '3x12 repeticiones', 'image_uri' => ''],
            ['id' => 69, 'name' => 'Peso muerto rumano', 'description' => '4x8 repeticiones', 'image_uri' => ''],
            ['id' => 70, 'name' => 'Flexiones con TRX', 'description' => '3x10 repeticiones', 'image_uri' => ''],
            ['id' => 71, 'name' => 'Battle Ropes', 'description' => '4x30 segundos', 'image_uri' => ''],
            ['id' => 72, 'name' => 'Elevación de talones con peso', 'description' => '3x15 repeticiones', 'image_uri' => ''],
            ['id' => 73, 'name' => 'Press de banca con mancuernas', 'description' => '4x10 repeticiones', 'image_uri' => ''],
            ['id' => 74, 'name' => 'Step-ups con peso', 'description' => '3x12 cada pierna', 'image_uri' => ''],
            ['id' => 75, 'name' => 'Plancha con toque de hombros', 'description' => '3x40 segundos', 'image_uri' => ''],
            ['id' => 76, 'name' => 'Snatch con mancuerna', 'description' => '3x8 cada lado', 'image_uri' => ''],
            ['id' => 77, 'name' => 'Dominadas con lastre', 'description' => '4x8 repeticiones', 'image_uri' => ''],
            ['id' => 78, 'name' => 'Golpe de balón medicinal', 'description' => '3x12 repeticiones', 'image_uri' => ''],
            ['id' => 79, 'name' => 'Sentadillas pistol', 'description' => '3x8 cada pierna', 'image_uri' => ''],
            ['id' => 80, 'name' => 'Plancha con giro de torso', 'description' => '3x30 segundos cada lado', 'image_uri' => ''],
            ['id' => 81, 'name' => 'Salto lateral con banda', 'description' => '3x12 cada lado', 'image_uri' => ''],
            ['id' => 82, 'name' => 'Press de pecho con banda de resistencia', 'description' => '3x10 repeticiones', 'image_uri' => ''],
            ['id' => 83, 'name' => 'Remo con kettlebell', 'description' => '4x12 repeticiones', 'image_uri' => ''],
            ['id' => 84, 'name' => 'Sentadilla con balón medicinal', 'description' => '3x15 repeticiones', 'image_uri' => ''],
            ['id' => 85, 'name' => 'Flexiones explosivas', 'description' => '3x10 repeticiones', 'image_uri' => ''],
            ['id' => 86, 'name' => 'Elevación de piernas en barra', 'description' => '4x12 repeticiones', 'image_uri' => ''],
            ['id' => 87, 'name' => 'Plancha con desplazamiento', 'description' => '3x30 segundos', 'image_uri' => ''],
            ['id' => 88, 'name' => 'Swing con kettlebell a una mano', 'description' => '3x15 cada lado', 'image_uri' => ''],
            ['id' => 89, 'name' => 'Curl de bíceps en banco inclinado', 'description' => '3x12 repeticiones', 'image_uri' => ''],
            ['id' => 90, 'name' => 'Step-ups con barra', 'description' => '3x10 cada pierna', 'image_uri' => ''],
            ['id' => 91, 'name' => 'Jumping lunges con mancuernas', 'description' => '3x12 cada pierna', 'image_uri' => ''],
            ['id' => 92, 'name' => 'Remo con polea baja', 'description' => '4x12 repeticiones', 'image_uri' => ''],
            ['id' => 93, 'name' => 'Sentadilla lateral', 'description' => '3x10 cada lado', 'image_uri' => ''],
            ['id' => 94, 'name' => 'Flexión en anillas', 'description' => '3x8 repeticiones', 'image_uri' => ''],
            ['id' => 95, 'name' => 'Fondos en paralelas con peso', 'description' => '4x10 repeticiones', 'image_uri' => ''],
            ['id' => 96, 'name' => 'Dragon Squat', 'description' => '3x10 cada pierna', 'image_uri' => ''],
            ['id' => 97, 'name' => 'Press de hombros con barra', 'description' => '4x10 repeticiones', 'image_uri' => ''],
            ['id' => 98, 'name' => 'Plancha con elevación de piernas', 'description' => '3x30 segundos cada pierna', 'image_uri' => ''],
            ['id' => 99, 'name' => 'Sprint con trineo', 'description' => '4x20 metros', 'image_uri' => ''],
            ['id' => 100, 'name' => 'Desplantes laterales con peso', 'description' => '3x12 cada lado', 'image_uri' => ''],
            ['id' => 101, 'name' => 'Sentadilla con salto', 'description' => '3x12 repeticiones', 'image_uri' => ''],
            ['id' => 102, 'name' => 'Press de banca declinado', 'description' => '4x10 repeticiones', 'image_uri' => ''],
            ['id' => 103, 'name' => 'Remo unilateral con mancuerna', 'description' => '3x12 cada lado', 'image_uri' => ''],
            ['id' => 104, 'name' => 'Extensiones de cuádriceps', 'description' => '3x15 repeticiones', 'image_uri' => ''],
            ['id' => 105, 'name' => 'Plancha sobre balón medicinal', 'description' => '3x45 segundos', 'image_uri' => ''],
            ['id' => 106, 'name' => 'Elevación de gemelos en máquina', 'description' => '4x20 repeticiones', 'image_uri' => ''],
            ['id' => 107, 'name' => 'Flexiones en pica', 'description' => '3x10 repeticiones', 'image_uri' => ''],
            ['id' => 108, 'name' => 'Russian Twist con balón', 'description' => '3x20 repeticiones', 'image_uri' => ''],
            ['id' => 109, 'name' => 'Fondos con agarre estrecho', 'description' => '4x10 repeticiones', 'image_uri' => ''],
            ['id' => 110, 'name' => 'Plancha con resistencia elástica', 'description' => '3x40 segundos', 'image_uri' => ''],
            ['id' => 111, 'name' => 'Levantamiento turco con kettlebell', 'description' => '3x6 cada lado', 'image_uri' => ''],
            ['id' => 112, 'name' => 'Sprint en escaleras', 'description' => '4x20 segundos', 'image_uri' => ''],
            ['id' => 113, 'name' => 'Peso muerto con trap bar', 'description' => '4x8 repeticiones', 'image_uri' => ''],
            ['id' => 114, 'name' => 'Press de hombros sentado', 'description' => '3x12 repeticiones', 'image_uri' => ''],
            ['id' => 115, 'name' => 'Elevación de piernas con banda', 'description' => '3x15 repeticiones', 'image_uri' => ''],
            ['id' => 116, 'name' => 'Flexiones con banda de resistencia', 'description' => '3x12 repeticiones', 'image_uri' => ''],
            ['id' => 117, 'name' => 'Kettlebell Clean', 'description' => '3x10 cada lado', 'image_uri' => ''],
            ['id' => 118, 'name' => 'Remo en barra en pronación', 'description' => '4x12 repeticiones', 'image_uri' => ''],
            ['id' => 119, 'name' => 'Sentadilla con resistencia elástica', 'description' => '3x15 repeticiones', 'image_uri' => ''],
            ['id' => 120, 'name' => 'Plancha con desplazamiento lateral', 'description' => '3x30 segundos', 'image_uri' => ''],
        ]);
    }
}
